mybatis:
  type-aliases-package:
    com.example.demo
  mapper-locations:
    classpath:mapping/*.xml
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 10000
      min-idle: 2
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      #  是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      validation-query: select 1 from dual
      validation-query-timeout: 100000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。 建议false
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能 ，建议false
      test-on-return: false
      test-while-idle: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat


